### ISSUE TITLE
No subscription functions on Customer object, no nextPage on Customer object.

### ISSUE THREAD

**Issue by sanchezand** [conekta/conekta-node#90] opened 2019-10-18 22:07 UTC
When getting a customer from an id, documentation says to pause a customer's subscription you call `customer.subscription.pause`, but the customer object doesnt include any subscription object or functions to pause or cancel a subscription.

Tests:
`
var customer = await conekta.Customer.find(customer_id);
console.log(Object.keys(customer));
`
This prints:
`
[ '_id',
  'classUrl',
  'children_resources',
  '_json',
  '_items',
  'listObjectsToArray',
  'toObject',
  'toArray',
  'build_children',
  'get',
  'post',
  'put',
  'del',
  'custom',
  'where',
  'find',
  'create',
  'update',
  'delete',
  'createCard',
  'createSubscription',
  'createShippingContact',
  'createPaymentSource',
  'payment_sources' ]
`

Also there's no nextPage function for searching customers. Charge and Order do have nextPage.

**Comment by leofischer** [comment] 2019-11-27 01:31
This sounds like a bug to me.

**Comment by leofischer** [comment] 2019-12-08 21:39
I have added a PR for the missing .nextPage() function and fleshed out the specs for `customer.subscription` methods.  Unfortunately I cannot reproduce the `customer.subscription` error mentioned, but you can see how I am accessing it here: https://github.com/conekta/conekta-node/pull/97/files#diff-c1129c8b045390789fa8ff62f2c6b4a9R1260.  @sanchezand, can you confirm if this answers your question?

**Comment by leofischer** [comment] 2020-01-10 04:29
@sanchezand - these changes have now been merge in the latest release https://github.com/conekta/conekta-node/releases/tag/4.0.1.  Can you confirm this works as expected?  I will leave this issues open for another 2 weeks, and there are no further comments will close it as completed

**Closed** 2023-08-02 15:12 UTC
Labels: enhancement, workinprogress
